### ISSUE TITLE
Non case sensitive

### ISSUE THREAD

**Issue by jasonlaw** [roshanrahman/profanity_filter#2]
Hi @roshanrahman ,

Could you please make the censor words non case sensitive?
For now, it will censor word f*** but not F***.

Thank you!

**Comment by roshanrahman** [comment]
Hi @jasonlaw, that's a good idea to provide a non case-sensitive option right in the Filter itself. Meanwhile, you can get similar functionality by passing the string to the filter methods converted to lowercase, like so: `'my string here'.toLowerCase()`

**Comment by jasonlaw** [comment]
Hi @roshanrahman,
I am afraid passing lower case to the filter method doesn't meet my requirement. We need to maintain the original capital case if it is not being censored. 

Looking forward for this feature to be built into the filter method. 

Thank you very much for this great package.
